import { TipoProducao, FormatoProducao } from "../types/solicitacao";

export const FORMATOS_POR_TIPO: Record<TipoProducao, FormatoProducao[]> = {
	EVENTO_IN_LOCO: ["ANIMACOES_EVENTOS_IN_LOCO"],

	EVENTO_EM_ESTUDIO: [
		"LIVE_PRE_GRAVADA",
		"LIVE_PRESENCIAL_ESTUDIO",
		"CRIACAO_EDICAO_ANIMACOES",
	],

	VIDEO_INSTITUCIONAL: [
		"LIVE_PRE_GRAVADA",
		"LIVE_PRESENCIAL_ESTUDIO",
		"LIVE_REMOTA",
		"PODCAST_MESACAST",
		"GRAVACAO_PROGRAMA",
		"CRIACAO_EDICAO_ANIMACOES",
	],

	GRAVACAO_CHAMADA: ["SHORTS_REELS"],

	GRAVACAO_VIDEOAULA: [
		"LIVE_PRE_GRAVADA",
		"LIVE_PRESENCIAL_ESTUDIO",
		"GRAVACAO_PROGRAMA",
		"CRIACAO_EDICAO_ANIMACOES",
	],

	EDICAO: ["CRIACAO_EDICAO_ANIMACOES", "SHORTS_REELS"],
};
